import { NgModule } from '@angular/core';
import {
  LucideAngularModule,
  Settings,
  Building2,
  Landmark,
  Users,
  IdCard,
  User,
  ShieldCheck,
  LockKeyhole,
  Package,
  Tag,
  Grid,
  UserRound,
  Hash,
  Box,
  Briefcase,
  LayoutGrid,
  Truck,
  Percent,
  Ruler,
  Droplet,
  ShoppingCart,
  FilePlus,
  FileX,
  DollarSign,
  FilePlus2,
  FileX2,
  ChevronDown,
  Search,
  Download,
  Plus,
  Save, // ✅ add these three
  FileSpreadsheet,
  FileCode,
  FileText,
  
} from 'lucide-angular';

@NgModule({
  imports: [
    LucideAngularModule.pick({
      Settings,
      Building2,
      Landmark,
      Users,
      IdCard,
      User,
      ShieldCheck,
      LockKeyhole,
      Package,
      Tag,
      Grid,
      UserRound,
      Hash,
      Box,
      Briefcase,
      LayoutGrid,
      Truck,
      Percent,
      Ruler,
      Droplet,
      ShoppingCart,
      FilePlus,
      FileText,
      FileX,
      DollarSign,
      FilePlus2,
      FileX2,
      ChevronDown,
      Search,
      FileSpreadsheet,
      FileCode,
      Download,
      Plus,
      Save,
    }),
  ],
  exports: [LucideAngularModule],
})
export class IconsModule {}
